import io.ktor.client.*
import io.ktor.client.engine.js.*
import io.ktor.client.plugins.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.plugins.cookies.*
import io.ktor.serialization.kotlinx.json.*

// Provided by config.js, generated by Gradle
external val SERVER_URL: String

val httpClient = HttpClient(Js) {
    install(ContentNegotiation) {
        json(Json)
    }
    install(HttpCookies)

    defaultRequest {
        url(SERVER_URL)
    }
}
